In [1]:
import numpy as np
from hmmlearn import hmm

In [2]:
# 设定隐藏状态的集合
states = ["box 1", "box 2", "box3"]
n_states = len(states)

# 设定观察状态的集合
observations = ["red", "white"]
n_observations = len(observations)

# 设定初始状态分布
start_probability = np.array([0.2, 0.4, 0.4])

# 设定状态转移概率分布矩阵
transition_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.3, 0.5, 0.2],
  [0.2, 0.3, 0.5]
])

# 设定观测状态概率矩阵
emission_probability = np.array([
  [0.5, 0.5],
  [0.4, 0.6],
  [0.7, 0.3]
])

In [4]:
# 设定模型参数
model = hmm.MultinomialHMM(n_components=n_states)
# 设定初始状态分布
model.startprob_ = start_probability
# 设定状态转移概率矩阵
model.transmat_ = transition_probability
# 设定观测状态概率矩阵
model.emissionprob_ = emission_probability

In [5]:
# 设定观测序列
seen = np.array([[0, 1, 0]]).T

In [6]:
seen

array([[0],
       [1],
       [0]])

In [10]:
observations

['red', 'white']

In [12]:
seen.flatten()

array([0, 1, 0])

In [13]:
",".join(map(lambda x: observations[x], seen.flatten()))

'red,white,red'

In [14]:
print("球的观测顺序为:\n", ",".join(map(lambda x: observations[x], seen.flatten())))

球的观测顺序为:
 red,white,red


In [15]:
# 维特比 - 模型训练
box = model.predict(seen)

In [16]:
box

array([2, 2, 2])

In [17]:
print("盒子最可能的隐藏状态顺序为:\n", ",".join(map(lambda x: states[x], box)))

盒子最可能的隐藏状态顺序为:
 box3,box3,box3


In [18]:
# 观测序列的概率的问题
model.score(seen)

-2.038545309915233

In [19]:
import math

math.exp(-2.038545309915233)

0.13021800000000003